Traceback (most recent call last):
  File "/home/hell/Desktop/UKAEA/Knowledge-Base/.venv/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/hell/Desktop/UKAEA/Knowledge-Base/.venv/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/hell/Desktop/UKAEA/Knowledge-Base/.venv/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/hell/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/hell/Desktop/UKAEA/Knowledge-Base/.venv/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/hell/Desktop/UKAEA/Knowledge-Base/.venv/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/hell/Desktop/UKAEA/Knowledge-Base/.venv/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import s3fs

# Create a connection to the S3 bucket
fs = s3fs.S3FileSystem(
    key = 'minioadmin',
    secret = 'minioadmin',
    client_kwargs = {'endpoint_url': 'http://localhost:9000'}
)

# Create a bucket
fs.mkdir('my-bucket-2') # Create a bucket

# Upload a file to the bucket
fs.put('images/minui_web_ui.png', 'my-bucket-2/images/minui_web_ui.png') # Upload the python file itself to the bucket

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01ms3fs[39;00m
[1;32m      3[0m [38;5;66;03m# Create a connection to the S3 bucket[39;00m
[1;32m      4[0m fs [38;5;241m=[39m s3fs[38;5;241m.[39mS3FileSystem(
[1;32m      5[0m     key [38;5;241m=[39m [38;5;124m'[39m[38;5;124mminioadmin[39m[38;5;124m'[39m,
[1;32m      6[0m     secret [38;5;241m=[39m [38;5;124m'[39m[38;5;124mminioadmin[39m[38;5;124m'[39m,
[1;32m      7[0m     client_kwargs [38;5;241m=[39m {[38;5;124m'[39m[38;5;124mendpoint_url[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124mhttp://localhost:9000[39m[38;5;124m'[39m}
[1;32m      8[0m )

[0;31mModuleNotFoundError[0m: No module named 's3fs'

