Traceback (most recent call last):
  File "/home/hell/Desktop/UKAEA/Knowledge-Base/.venv/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/hell/Desktop/UKAEA/Knowledge-Base/.venv/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/hell/Desktop/UKAEA/Knowledge-Base/.venv/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/hell/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/hell/Desktop/UKAEA/Knowledge-Base/.venv/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/hell/Desktop/UKAEA/Knowledge-Base/.venv/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/hell/Desktop/UKAEA/Knowledge-Base/.venv/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import intake

# Load the catalog

catalog = intake.open_catalog('data/catalog.yaml')

# List available datasets 
print(catalog)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mintake[39;00m
[1;32m      3[0m [38;5;66;03m# Load the catalog[39;00m
[1;32m      5[0m catalog [38;5;241m=[39m intake[38;5;241m.[39mopen_catalog([38;5;124m'[39m[38;5;124mdata/catalog.yaml[39m[38;5;124m'[39m)

[0;31mModuleNotFoundError[0m: No module named 'intake'

